package vista;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

//CONEXION A BASE DE DATOS
public class VentanaUsuarios extends javax.swing.JFrame {
    DefaultTableModel modelo=new DefaultTableModel();
    Statement ejecutar=null;
    Connection con;
    String driver="com.mysql.cj.jdbc.Driver";
    String user="root";
    String pass="";
    String url="jdbc:mysql://localhost:3306/dreamgifts";
    //Metodo CargarTabla
    protected void cargartabla(){

        modelo.setRowCount(0);
        String datos[]=new String[6];
        String query="select * from usuarios";
        ResultSet rs;
        try {
            ejecutar=con.createStatement();            
            rs=ejecutar.executeQuery(query);
            while(rs.next()==true){
                datos[0]=rs.getString("USU_ID_USUARIO");
                datos[1]=rs.getString("USU_NOMBRE");
                datos[2]=rs.getString("USU_APELLIDO");
                datos[3]=rs.getString("USU_USERNAME"); 
                datos[4]=rs.getString("USU_CLAVE");
                datos[5]=rs.getString("USU_ESTADO"); 
                modelo.addRow(datos);
            }
            tablaUsuarios.setModel(modelo);
        } catch (Exception e){            
        }        
    }
    
    
    //Mostrar si hay conexion con metodo conectar
    public void conectar(){
        con=null;
        try {
            Class.forName(driver);
            con=(Connection)DriverManager.getConnection(url, user, pass);
            if(con!=null){
               txtInformacion.setText("Conexion exitosa"); 
            }            
        }catch (Exception e){ 
               txtInformacion.setText("Sin conexion!!! "+e);
        }
    }

    /**
     * Creates new form VentanaUsuarios
     */
    //constructor
    public VentanaUsuarios() {
        initComponents();
        modelo.addColumn("ID");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("APELLIDO");
        modelo.addColumn("NOMBRE USUARIO");
        modelo.addColumn("CLAVE");
        modelo.addColumn("ESTADO");          
          conectar();
          cargartabla();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnUsuariosEditar = new javax.swing.JButton();
        btnUsuariosDesactivar = new javax.swing.JButton();
        txtUsuarioNombre = new javax.swing.JTextField();
        txtUsuarioUserName = new javax.swing.JTextField();
        txtUsuariosClave = new javax.swing.JTextField();
        txtUsuariosVerClave = new javax.swing.JTextField();
        btnUsuariosCancelar = new javax.swing.JButton();
        btnUsuariosGuardar = new javax.swing.JButton();
        Jnombre = new javax.swing.JLabel();
        Jusername = new javax.swing.JLabel();
        Jingclave = new javax.swing.JLabel();
        Jvericlave = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtInformacion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btnUsuarioEstadoActivo = new javax.swing.JRadioButton();
        btnUsuarioEstadoInactivo = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dream Gifts");

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuarios"));
        jPanel1.setForeground(new java.awt.Color(51, 51, 255));
        jPanel1.setToolTipText("Dreamgifts_Usuarios");

        btnUsuariosEditar.setBackground(new java.awt.Color(153, 153, 153));
        btnUsuariosEditar.setText("Modificar");
        btnUsuariosEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosEditarActionPerformed(evt);
            }
        });

        btnUsuariosDesactivar.setBackground(new java.awt.Color(153, 153, 153));
        btnUsuariosDesactivar.setText("Desactivar");
        btnUsuariosDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosDesactivarActionPerformed(evt);
            }
        });

        txtUsuarioNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioNombreActionPerformed(evt);
            }
        });

        txtUsuariosClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuariosClaveActionPerformed(evt);
            }
        });

        txtUsuariosVerClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuariosVerClaveActionPerformed(evt);
            }
        });

        btnUsuariosCancelar.setBackground(new java.awt.Color(153, 153, 153));
        btnUsuariosCancelar.setText("Cancelar");

        btnUsuariosGuardar.setBackground(new java.awt.Color(153, 153, 153));
        btnUsuariosGuardar.setText("Guardar");
        btnUsuariosGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuariosGuardarMouseClicked(evt);
            }
        });
        btnUsuariosGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosGuardarActionPerformed(evt);
            }
        });

        Jnombre.setText("Nombre");

        Jusername.setText("Nombre Usuario");

        Jingclave.setText("Ingrese clave");

        Jvericlave.setText("Verifique clave");

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 14)); // NOI18N
        jLabel5.setText("Usuarios Registrados");

        txtInformacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInformacionActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tablaUsuarios);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnUsuarioEstadoActivo.setText("Activo");

        btnUsuarioEstadoInactivo.setText("Inactivo");
        btnUsuarioEstadoInactivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuarioEstadoInactivoActionPerformed(evt);
            }
        });

        jLabel1.setText("Estado de usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Jnombre)
                                    .addComponent(Jusername)
                                    .addComponent(jLabel1))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnUsuarioEstadoActivo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUsuarioEstadoInactivo))
                                    .addComponent(txtUsuarioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUsuarioUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(43, 43, 43)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtUsuariosClave, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(250, 250, 250)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Jingclave)
                                                .addComponent(Jvericlave))
                                            .addComponent(btnUsuariosCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnUsuariosGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtUsuariosVerClave, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(22, 22, 22))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUsuariosEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnUsuariosDesactivar)
                        .addGap(33, 33, 33))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuariosClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jnombre)
                    .addComponent(Jingclave))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuarioUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuariosVerClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jusername)
                    .addComponent(Jvericlave))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsuariosCancelar)
                    .addComponent(btnUsuariosGuardar)
                    .addComponent(btnUsuarioEstadoActivo)
                    .addComponent(btnUsuarioEstadoInactivo)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnBuscar)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUsuariosEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuariosDesactivar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(240, 240, 240))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuariosClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuariosClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuariosClaveActionPerformed

    private void btnUsuariosGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosGuardarActionPerformed
        guardar(); 
        
     }
    //Metodo guardar
    protected void guardar(){   
        String mensajeError="";
        String query="";
        PreparedStatement preparar=null;
        if(txtUsuarioNombre.getText().isEmpty()==true){
            mensajeError=mensajeError+" Ingrese Nombre, ";
        }
        if(txtUsuarioUserName.getText().isEmpty()==true){
            mensajeError=mensajeError+" Ingrese Nombre de Usuario, ";            
        }
        if(txtUsuariosClave.getText().isEmpty()==true){
            mensajeError=mensajeError+" Ingrese Clave, ";
        }
        if(mensajeError.isEmpty()==true){
              query="insert into usuarios (USU_NOMBRE, USU_USERNAME, USU_CLAVE ) values ('"+txtUsuarioNombre.getText()+"','"+txtUsuarioUserName.getText()+"','"+txtUsuariosClave.getText()+"')"; 
            try{
                preparar=con.prepareStatement(query);
                preparar.executeUpdate();
                cargartabla();
            }catch (Exception e) {
                
            }
        }
        else{
            JOptionPane.showMessageDialog(null, mensajeError);
        }
    }//GEN-LAST:event_btnUsuariosGuardarActionPerformed

    private void txtInformacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInformacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInformacionActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtUsuariosVerClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuariosVerClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuariosVerClaveActionPerformed

    private void btnUsuariosDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosDesactivarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuariosDesactivarActionPerformed

    private void txtUsuarioNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioNombreActionPerformed

    private void btnUsuariosGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuariosGuardarMouseClicked
        
    }//GEN-LAST:event_btnUsuariosGuardarMouseClicked

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        int registro=tablaUsuarios.getSelectedRow();
        txtUsuarioNombre.setText(tablaUsuarios.getValueAt(registro, 1).toString());
        txtUsuarioUserName.setText(tablaUsuarios.getValueAt(registro, 3).toString());
        txtUsuariosClave.setText(tablaUsuarios.getValueAt(registro, 4).toString());
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void btnUsuariosEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosEditarActionPerformed
        PreparedStatement preparar=null;
        String query="update usuarios set USU_NOMBRE='"+txtUsuarioNombre.getText()+"', USU_USERNAME='"+txtUsuarioUserName.getText()+"', USU_CLAVE='"+txtUsuariosClave.getText()+"' where USU_ID_USUARIO='"+tablaUsuarios.getValueAt(tablaUsuarios.getSelectedRow(),0)+"'; ";
        try{
           preparar=con.prepareStatement(query);
           preparar.executeUpdate();
           cargartabla();
        }catch (Exception e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_btnUsuariosEditarActionPerformed

    private void btnUsuarioEstadoInactivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuarioEstadoInactivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuarioEstadoInactivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jingclave;
    private javax.swing.JLabel Jnombre;
    private javax.swing.JLabel Jusername;
    private javax.swing.JLabel Jvericlave;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JRadioButton btnUsuarioEstadoActivo;
    private javax.swing.JRadioButton btnUsuarioEstadoInactivo;
    private javax.swing.JButton btnUsuariosCancelar;
    private javax.swing.JButton btnUsuariosDesactivar;
    private javax.swing.JButton btnUsuariosEditar;
    private javax.swing.JButton btnUsuariosGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtInformacion;
    private javax.swing.JTextField txtUsuarioNombre;
    private javax.swing.JTextField txtUsuarioUserName;
    private javax.swing.JTextField txtUsuariosClave;
    private javax.swing.JTextField txtUsuariosVerClave;
    // End of variables declaration//GEN-END:variables
}
